### ISSUE TITLE
Exported report does not show icons when opened in IE

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#1875] opened 2019-12-17 01:01 UTC
## Describe the bug
The report does not show icons when opened in Internet Explorer

Here is a picture of how the report looks in IE
![image](https://user-images.githubusercontent.com/19158512/70955318-41521a80-2025-11ea-83a1-537af18438a8.png)

**To Reproduce**

1. Go to 'www.google.com'
2. Click on the Accessibility Insights extension
3. Select 'FastPass'
4. In FastPass, Automated Checks, select 'Export Result'
5. Save the exported result
6. Open the exported file with IE
7. See error

## Expected behavior

I expect the icons to show in the report, like they do in Chrome (pictured below)
![image](https://user-images.githubusercontent.com/19158512/70955343-5a5acb80-2025-11ea-929c-8200cc45f2b1.png)

## Context (please complete the following information)

- OS Name & Version: Windows 10
- AI-Web Version & Environment:  Canary 2019.12.16.1956
- Browser Version:  Internet Explorer
- Target Page:  www.google.com

**Comment by ferBonnin** [comment] 2020-01-06 21:07
Per conversation with Peter, lets time box the investigation for this and find out if its simply that what we are using is not supported by IE or if there is an easy tweak we can do to support it. In documentation for Web, we do mention that we work for Chrome and Edge insider only.

**Comment by dbjorge** [comment] 2020-05-21 01:02
#2737 fixes the most glaring usability issues. Most other issues stem from our use of CSS variables (which IE doesn't support) for colors. Investigating a possible update to improve how we manage CSS colors such that we might be able to support this in the future (in a separate PR from #2737).

**Comment by ferBonnin** [comment] 2020-07-21 19:16
@peterdur per dbjorge comment above looks like we have fixed the bigger usability issues and fixing the CSS colors will require more investigation since IE doesn't support it at the moment. are we ok with closing this issue with a partial fix?

**Comment by peterdur** [comment] 2020-08-04 18:56
@ferBonnin here's what the report currently looks like in IE:
![image](https://user-images.githubusercontent.com/1752950/89329838-3bf12100-d644-11ea-8be3-8218fe6af688.png)
There's some regression in that most of the icons are no longer visible; since the earlier screenshot we moved to using CSS variables more extensively around icons for high contrast support purposes - see #3064 for more details (and really we probably should be using CSS variables even more, which would make the colored circles and icons disappear entirely). 
Even without the icons, though, the report is navigable and all the instance information can be accessed. I think this meets an appropriate bar for Internet Explorer support. I'm OK with closing this issue as-is.

**Closed** 2020-08-04 20:01 UTC
Labels: bug, status: needs investigation
