### ISSUE TITLE
Need to enhance the tab stop html report as element is reachable but its showing as unreachable and needs review

### ISSUE THREAD

**Issue by satishnik** [microsoft/accessibility-insights-web#6625] opened 2023-05-12 06:37 UTC
I am using the chrome browser extension for accessibility testing. I am running the tab stop check on the application. But after the tab stop execution, the html report will shows element is unreachable and needs review. If user is able to access the web element using keyboard without any issue then it should not highlight as issue in the html report. 

Lets suppose I am tabbing 10 elements then html report shows that 10 elements comments as "
**Comment | [Automatically detected, needs review] Unreachable element**:"

**Comment by codeofdusk** [comment] 2023-05-14 22:54
Hello @satishnik,

Thank you for your report. Could you please provide a test case and both expected and observed behaviour? If you're able to create a minimal example, you might want to upload it to [CodePen](https://codepen.io/) for sharing.

**Comment by satishnik** [comment] 2023-05-15 05:20
Hi @codeofdusk 
Please find the test case for the facebook. Please refer the attached screenshot and extension report. On Facebook application the textbox for email, password, Log In button and other links are reachable using keyboard tab button but in the report its showing as the unreachable element.
<img width="713" alt="image" src="https://github.com/microsoft/accessibility-insights-web/assets/123003457/641083ba-838d-4754-b7b3-8c94039ad979">
[](url)


<img width="944" alt="Facebook" src="https://github.com/microsoft/accessibility-insights-web/assets/123003457/d202dd2f-4501-4d0f-a50c-a8d62dc8c2f7">

**Comment by codeofdusk** [comment] 2023-05-15 21:03
Unfortunately, we're unable to reproduce this behaviour. Could you please provide a detailed, step-by-step process to follow to reproduce your issue?

CC @madalynrose

**Comment by satishnik** [comment] 2023-05-16 08:03
Hi @codeofdusk 
Please find below details steps to re-produced the issue.
1. Open www.Facebook.com on chrome Browser.
2. Open your Chrome Accessibility Insight for web extension.
3. Click on the FastPass on the chrome extension. It will open another window for Accessibility Insight for the web.
4. On newly open window of Accessibility Insight - On Left side Menu Bar, Click on the Tab Stops option.
5. Now Click on the Start over link which is present in the Top Right Corner of the window.
6. Once you click on the Start over link in previous step, it will navigate to Facebook window. 
7. Before starting the Tab stop, Just open the  Accessibility Insight for the web and wait till the popup with header "**Possible failures auto-detected**" appear on window.
<img width="413" alt="image" src="https://github.com/microsoft/accessibility-insights-web/assets/123003457/e766c88d-0c85-404d-a11d-02cb9b32a8a0">

8. In Above pop-up, Click on Got it button.
9. Now open the Facebook app window and start pressing TAB key until it completes the navigation on the page.
10. After tab stop finish, please verify the report. The report will contains incorrect information as per mentioned in the previous comment screenshot.

**Comment by satishnik** [comment] 2023-05-24 04:39
Hi @codeofdusk @nang4ally 
Do you have any update on this issue ? Any ETA for this ?

**Comment by DaveTryon** [comment] 2023-06-01 18:23
@peterdur Can you please update with your investigation results?

**Comment by DaveTryon** [comment] 2023-06-19 18:24
We'd like to update the instructions to make this clearer and not steer the user back to the extension halfway through the scan

**Comment by DaveTryon** [comment] 2023-06-29 21:03
@satishnik, the instructions here are bad. The intent of the test is that you tab through everything on the page _before_ bringing the focus back to the web extension. One the focus returns, any controls that weren't tabbed get marked as being inaccessible. We're working on a revision to the instructions.

**Comment by DaveTryon** [comment] 2023-06-29 21:03
@nang4ally, tagging you on this since we need revised instructions.

**Comment by DaveTryon** [comment] 2023-08-28 19:59
This was released with 2.39.0

**Closed by DaveTryon** 2023-08-28 19:59 UTC
