### ISSUE TITLE
Failure details dialog buttons are not clickable

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#365] opened 2019-03-14 20:53 UTC
## Describe the bug

On certain pages, after running automated checks and opening the "Failure details" dialog, it is not possible to click any of the buttons on the dialog.

**To Reproduce**

1. Navigate to [https://www.schwab.com/](https://www.schwab.com/)
2. Click the extension icon close to the right-top corner
3. Click on Ad hoc tools
4. Enable Automated checks by clicking on the toggle
5. On the page itself, click on any of the red exclamation marks to show the failure details
6. Click the Copy failure details
7. Paste the content of the clipboard (on any text editor)
8. Observe: failure details are not being copied to the clipboard, there is no toast from clicking the button

## Expected behavior

When the user click "Copy failure details", a toast with the text "Failure details copied" should appear, the failure details should be on the system clipboard

## Screenshots

**Working as expected scenario**
![01 - working correctly on goggle](https://user-images.githubusercontent.com/2837582/54390226-382fb980-465f-11e9-8b08-6fc0530e5969.gif)

**Not working as expected scenario**
![02 - not working correctly](https://user-images.githubusercontent.com/2837582/54390252-41b92180-465f-11e9-8961-b43b7d8d51ba.gif)

## Extension (please complete the following information)

- OS: Windows 10.0.17763 Build 17763
- Version: 2.0.4
- Chrome Version: 73.0.3683.75 (Official Build) (64-bit)
- Target Page: [https://www.schwab.com/](https://www.schwab.com/)

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
**yes**

**Comment by dbjorge** [comment] 2019-10-18 22:19
This still repros today against current master.

The root cause of this is that https://schwab.com is dynamically updating our buttons' onClick handlers as they get loaded into the DOM (it is this for all `<button>` elements, not looking for ours specifically).

I do not believe there is going to be any realistic way to fix for the general case short of finishing the "render the target page dialog in the shadow DOM" feature that we've been indefinitely deferring. I'm kicking this back to "ready for triage" in light of the new information about how costly it would be to fix this.

**Comment by ferBonnin** [comment] 2019-10-21 17:56
Per the investigation and cost to fix we are marking this as out of scope.

**Closed by ferBonnin** 2019-10-21 17:56 UTC
Labels: bug, resolution: out of scope, status: ready for triage

**Comment by dbjorge** [comment] 2019-10-21 18:04
Updated title to clarify the relatively specific scope of the issue
