### ISSUE TITLE
Card footer more actions button dots not centered

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#1509] opened 2019-10-17 23:58 UTC
## Describe the bug

The 3 dots in the "more actions" button in the card footer are not centered in the button/focus box.

**To Reproduce**

1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. Open the extension popup and click FastPass
3. Scroll down to a failure instance card
4. Hover over 3 dots in the card footer (or tab to this button to maintain the focus on it)
5. See that the 3 dots are not horizontally centered

## Expected behavior

The 3 dots should be horizontally centered in the "more actions" button

## Screenshots

![image](https://user-images.githubusercontent.com/48259897/67055785-47e41480-f0fe-11e9-9d5c-f8b0e6402e37.png)

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 10.0.18362 Build 18362
- Browser Version [e.g Chrome 71.0] Chrome 77.0.3865.120 (Official Build)
- Target Page [e.g www.bing.com] https://www.washington.edu/accesscomputing/AU/before.html
- Extension version: Insider 2.10.1

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by dbjorge** [comment] 2019-10-18 20:48
@lisli1: For resolving this, note that the issue is specific to release builds, so you should double check in canary rather than building from master

**Closed** 2019-10-21 19:52 UTC
Labels: bug, status: resolved
