### ISSUE TITLE
General error message for Copy failure details on non-HTTPS and non-localhost webpages

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#3803] opened 2021-01-07 01:53 UTC
## Describe the bug

"Copy failure details" from an issue dialog on a non-secure webpage, such as http://www.washington.edu/accesscomputing/AU/before.html, does not work due to Chrome disabling clipboard access for security reasons (see [Additional context](#additional-context)). The error message says "Failed to copy failure details. Please try again."

**To Reproduce**

1. Go to http://www.washington.edu/accesscomputing/AU/before.html
2. Open extension popup
3. Run FastPass
4. Open an issue dialog by clicking on any ! in the highlighted issue boxes on the target page
5. Select "Copy failure details"
6. See toast with message "Failed to copy failure details. Please try again."

## Expected behavior

Have the toast error message be more descriptive of why the copying is failing, or print an error in the console that points out the issue.

## Context (please complete the following information)

- OS Name & Version:  Windows Version 10.0.19042 Build 19042
- AI-Web Version & Environment:  Production 2.23.0
- Browser Version: Edge Version 87.0.664.66 (Official build) (64-bit)
- Target Page: http://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

According to https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined/51823007#51823007, Chrome disables the clipboard for any page that does not have a secure origin (HTTPS or localhost) for security reasons.

**Comment by ferBonnin** [comment] 2021-01-11 21:15
Per conversation with Peter, there isn't something we can do to make this functionality work in unsafe sites (both Edge and Chrome)
We should have a clearer message on why copy failure details is not working (and will not work in this type of sites) instead of asking users to try again.

Since this issue is only reproduced in the target page pop-up, we should:
1) In the toast, keep the message "Failed to copy failure details." remove the section to try again
2) similar to the _inspect HTML_ button, add text below the button to indicate that this functionality will only work in the details page.

**Comment by codeofdusk** [comment] 2021-04-23 18:41
I can't repro this on Chrome 91.0.4472.19 running Accessibility Insights 2.25.0 on Windows 10 21H1.

1. Visit the linked page.
2. Press alt+shift+t, arrow to accessibility insights and press enter. Observe that "not secure" is displayed on the toolbar.
3. Navigate to "fast pass" and activate it.
4. Wait for automated scan to complete, observe 20 failures detected. Navigate by heading to one of the failures and expand it.
5. Select "more actions" then copy from the menu.

The failure text is copied to the clipboard for me, no error reported.

As an aside, I can't find an option to "inspect HTML" and a `git grep` for the string (including a few variations) in the repo was not fruitful.

Am I looking in the wrong places? Seems like a good first issue, but new to both Accessibility Insights and web extension development.

Cc @RobGallo.

**Comment by ferBonnin** [comment] 2021-04-23 18:57
@codeofdusk thanks for looking into this! This only happens in the target page when you select the '!'exclamation icons, but not from the FastPass page

**Comment by codeofdusk** [comment] 2021-04-23 20:29
What is the accessible label for the exclamation mark icon? (I'm using a screen reader).

**Comment by kennyzhen13** [comment] 2021-04-23 22:18
Hi @codeofdusk I have explored this issue a bit on a [branch on my fork](https://github.com/kennyzhen13/accessibility-insights-web/tree/copy-failure-details-fix). Please let me know if you have any feedback!

**Comment by DaveTryon** [comment] 2021-05-21 22:07
Confirmed fixed in release 2.26.1 (currently in Insider channel)

**Closed by DaveTryon** 2021-05-21 22:07 UTC
Labels: bug, good first issue, help wanted, status: active
