### ISSUE TITLE
17.6 Text spacing helper flaw

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/accessibility-insights-web#6553] opened 2023-03-31 11:15 UTC
**Description**
The styling injected by 17.6 when you enable the text helper is not specific enough and ends up giving a false positive of failure when in fact the site is fine.

In this specific case it is the line height that does not get altered.

**To Reproduce**

1. Go to https://www.communitydirectory.norfolk.gov.uk/
2. Enable the extension and/or click the extension button on next to address bar.
3. Choose Assement option.
4. Scroll to and expand 17 adaptable content and then click 17.6 Text spacing
5. Turn on the visual helper

## Expected behavior
The letter spacing, word spacing, line height and space after paragraphs should change.

## Screenshots
Using extensions
![image](https://user-images.githubusercontent.com/28951140/229104619-a6249d16-d503-4ccb-a261-5b542fa63ea9.png)

If I used a JS bookmarklet from https://codepen.io/stevef/pen/YLMqbo and toggle it on then I get the following as expected:
![image](https://user-images.githubusercontent.com/28951140/229104929-cd02072d-fb81-4dcb-a598-9e94164d3fa3.png)

## Context (please complete the following information)

- OS Name & Version: Windows 11 22H2 (Build 22621.1413)
- AI-Web Version & Environment: v2.373 (official release)
- Browser Version: MS Edge 113.0.1769.0 (canary 64 bit) and Google Chrome 111.0.5563.147 (Official Build) (64-bit)
- Target Page: https://www.communitydirectory.norfolk.gov.uk/

## Are you willing to submit a PR?

I'm raising this merely because a client is using this tool to verify our work and is raising issues because of it.

## Did you search for similar existing issues?

Yes

## Additional context

The problem appears to be that the extension is injected styles that are not specific enough to various elements. The example JS bookmarklet applies styles to * and thus appears to have no issues.

**Comment by JGibson2019** [comment] 2023-04-25 23:01
@peterlukerow This is a duplicate of an existing issue in our repo, https://github.com/microsoft/accessibility-insights-web/issues/4800. We will be closing this issue but you can refer to the other one for updates!

**Closed by JGibson2019** 2023-04-25 23:01 UTC
Labels: bug, status: ready for triage
