### ISSUE TITLE
[Bug] Next requirement button doesn't expose "next" or ">" behavior to ATs 

### ISSUE THREAD

**Issue by RobGallo** [microsoft/accessibility-insights-web#3688] opened 2020-11-23 19:52 UTC
## Describe the bug

Quoted from Rob's original bug below: 

"Note: The button gives no accessible indication it is meant to move to the next requirement. My understanding is there is a visual _next_ indicator (the presence of a rightward pointing arrow). This could be resolved by 

1. Labeling the button simply as "next" or "next requirement" for everyone
2. Adding a character in the accessible label which connotes _next_ such as '>' or '→'.
3. Adding a brief text indicator to the accessible label before or after the text of the next requirement, e.g., "next: On focus"
"

Note: everything below this point is the original bug text - we were unable to reproduce the stale accessible name behavior on 10/20/21. However, the button context concern is still present, so we've renamed the bug.

----

> 
> ## Describe the bug
> 
> When going through the assessments, the accessible name of the button to move to the next requirement gives the name of the currently visible requirement, instead of the next requirement.
> 
> This issue effects navigating with JAWS virtual cursor. For some reason, it did not seem to effect NVDA using the browse cursor, although there is obviously an issue given the Chrome accessible tree isn't updating in a timely manner.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open AI-Web for any web page
> 2. Click the "Assessment" link
> 3. Click the hamburger button at the top left (the accessible name is "assessment - all tests and requirements list")
> 4. Expand the "Keyboard" section
> 5. Choose the "Keyboard navigation" link
> 6. At the bottom right of the page, choose the "No keyboard traps" button
> 7. When the new page loads, use the Chrome developer tools to examine the accessibility tree. You will find the button at the bottome right hand corener which moves to the next requirement still has the accessible label "No keyboard traps". It should have the accessible label "On focus".
> 
> ## Expected behavior
> 
> 1. Force the accessibility tree to update in a timely manner so that the name of the button is rendered correctly to screen readers
> 2. Change the name of the button to "Next requirement", thereby obviating the need for a timely refresh.
> 
> Note: The button gives no accessible indication it is meant to move to the next requirement. My understanding is there is a visual _next_ indicator (the presence of a rightward pointing arrow). This could be resolved by 
> 
> 1. Labeling the button simply as "next" or "next requirement" for everyone
> 2. Adding a character in the accessible label which connotes _next_ such as '>' or '→'.
> 3. Adding a brief text indicator to the accessible label before or after the text of the next requirement, e.g., "next: On focus"
> 
> ## Context (please complete the following information)
> 
> - OS Name & Version: Windows Version	10.0.19042 Build 19042
> - AI-Web Version & Environment: 2.22.0 production
> - Browser Version: Google Chrome Version 87.0.4280.66
> - Target Page: https://www.bing.com
> 
> ## Are you willing to submit a PR?
> 
> No. Never. Wouldn't dream of it.
> 
> ## Did you search for similar existing issues?
> 
> Yes
> 
> ## Additional context
> 
>

**Comment by ferBonnin** [comment] 2020-11-23 21:05
Per conversation with Peter, lets investigate this for a day. If we can't find what the issue is and a possible solution, lets change all the buttons to say "Next requirement" instead

**Comment by waabid** [comment] 2021-01-07 21:40
I looked into this a bit and it seems to be an issue with chrome.

I created a simple JS fiddle example that shows this behavior as well: https://jsfiddle.net/vf2udxco/1/.

I will look into maybe creating a chromium bug and seeing from there separately from what we want to do here.

**Comment by ferBonnin** [comment] 2021-02-01 21:06
@waabid @iamrafan let's please file a bug on Chromium. Marking this as blocked.

**Comment by ferBonnin** [comment] 2021-04-12 18:37
doing a friendly ping on this, did we filed a bug on Chromium? @iamrafan

**Comment by iamrafan** [comment] 2021-05-19 17:29
No, it needs discussion. I will start an email thread

**Closed** 2021-10-20 18:27 UTC
Labels: bug, status: ready for triage
