### ISSUE TITLE
button-name rule not considering label linked to button

### ISSUE THREAD

**Issue by cchengt** [microsoft/accessibility-insights-web#5912] opened 2022-08-12 15:51 UTC
## Describe the bug

Hello, I have <label /> linked to text-less <button /> via the label "for" attribute; I assumed this would be enough to pass the button-name check but it didn't. When tested with Narrator, the screen reader reads out the button's associated label.

**To Reproduce**
Fast check this HTML:
<!DOCTYPE html>
<HTML lang="en-US">
    <HEAD>
        <TITLE>test</TITLE>
    </HEAD>
    <BODY>
        <label for="button0">Test</label>
        <button id="button0"></button>
    </BODY>
</HTML>

2. Click on '...'
3. Scroll down to '...'

## CodePen repro example

https://codepen.io/cchengts/pen/VwXGgRP

## Expected behavior

No button-name violation

## Context (please complete the following information)

- OS Name & Version: Windows 11
- AI-Web Version & Environment: 2.32.0
- Browser Version: Edge Version 104.0.1293.47 (Official build) (64-bit)
- Target Page: N/A

## Are you willing to submit a PR?

Maybe, I'm not sure how involved it would be

## Did you search for similar existing issues?

Yes, but none found

**Comment by shanisebarona** [comment] 2022-08-12 21:28
Hi @cchengt! I was able to reproduce the button-name error you are referencing. Looks like per [Using label elements to associate text labels with form controls](https://www.w3.org/WAI/WCAG21/Techniques/html/H44), `label` is not to be used for a button. 

Passing examples and alternatives can be found here: [button-name](https://accessibilityinsights.io/info-examples/web/button-name/).

**Comment by cchengt** [comment] 2022-08-15 14:50
I see, thanks for linking the w3 document. It looks this issue is not a bug then.

**Comment by sfoslund** [comment] 2022-08-15 15:12
Thanks for confirming @cchengt! Is there anything else we can help with or can we go ahead and close this issue?

**Closed** 2022-08-22 20:01 UTC
Labels: bug, status: needs author feedback, status: no recent activity
