### ISSUE TITLE
Headings disappear on scrolling the page

### ISSUE THREAD

**Issue by Anschur** [microsoft/accessibility-insights-web#1585] opened 2019-10-31 12:37 UTC
## Describe the bug

Heading outline on page disappears when scrolling the page.

**To Reproduce**

1. Go to https://www.office.com/search?auth=2&q=office (Office.com search result page)
2. Activate Headings on the Accessibility Insights extension in Chrome (Ad-hoc tools)
3. Heading outline appear on page
4. Scroll page
5. Heading outline disappears

## Expected behavior

Heading outline to remain on page when scrolling

## Extension (please complete the following information)

- OS: Windows
- Version 2.10.3 | Powered by axe-core 3.3.2
- Browser Version: Version 78.0.3904.70
- Target Page: www.office.com

**Comment by smoralesd** [comment] 2019-10-31 17:17
@Anschur thanks for reporting this issue. I'm able to repro it using all of the ad-hoc visualizations. This only happen this specific website (I see normal behavior on other websites) which may point to the root cause of this. We'll investigate and triage this issues soon.
In the meanwhile, there are a couple of workaround you may want to try to get you unblocked.
1. Maximize the browser window and zoom out until there is no scrollbar (no scrollbar means no way to trigger this issue)
2. Using Assessment -> Headings -> Heading function's visual helper I was able to retain the visualization after scrolling. It takes some milliseconds to update but the highlighting is there.

**Comment by smoralesd** [comment] 2019-11-05 00:01
closed by #1583

**Comment by ferBonnin** [comment] 2019-12-04 17:45
@smoralesd is this still blocked?

**Comment by ferBonnin** [comment] 2019-12-16 21:06
Hi @Anschur, the fix for this bug is now available in our [insider extension](https://chrome.google.com/webstore/detail/nnmjfbmebeckhpejobgjjjnchlljiagp). Could you please take a look and let us know if the issue is fixed for you?

**Comment by ferBonnin** [comment] 2019-12-20 19:07
Closing this bug as resolved, feel free to reactivate if needed.

**Closed by ferBonnin** 2019-12-20 19:07 UTC
Labels: bug, status: resolved

**Comment by Anschur** [comment] 2020-01-02 13:55
Works like a charm. Thanks :)
