### ISSUE TITLE
Text spacing link doesn't take user to the text spacing bookmarklet

### ISSUE THREAD

**Issue by jechols** [microsoft/accessibility-insights-web#1163] opened 2019-08-28 21:56 UTC
## Describe the bug

The link to download the "text spacing" bookmarklet takes me to the WCAG 2.1 page on w3c, but there's no bookmarklet to be found there.  I'm not sure if the link was supposed to be labeled differently or what, but I ended up having to search for the bookmarklet (and hope that what I found was the same one as what was meant to be used).

**To Reproduce**

1. In the Accessibility Insights window, do an assessment on something
2. Go to number 17, "Text legibility"
2. Click on number 6 in the "Requirements" section ("Text spacing")
3. Under "How to test", click the link to the "text spacing" bookmarklet
4. You'll be taken to `https://www.w3.org/TR/WCAG21/#dfn-https://www.html5accessibility.com/tests/tsbookmarklet.html`.  I believe the correct page would have been the last part of the link, `https://www.html5accessibility.com/tests/tsbookmarklet.html`
5. If you try to drag it into your bookmarks, it functions as a standard bookmark, taking you to the above-mentioned page.

## Expected behavior

Clicking the link should take me to the correct bookmarklet page.

## Extension (please complete the following information)

- OS: Windows
- Version 2.8.2
- Browser Version Chrome 76
- Target Page https://library.uoregon.edu/

## Are you willing to submit a PR?

Probably not - but it depends on the ease of fixing this and time investment

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment] 2019-08-28 23:51
Hi @jechols, thank you for reporting this issue. We can reproduce it and we will take a look to fix it. 
In the meantime, please use the following link: https://www.html5accessibility.com/tests/tsbookmarklet.html

**Comment by ferBonnin** [comment] 2019-08-29 21:31
this issue is resolved, keeping open until fix is in Prod :)
@jechols, if you want to take a look to the fix, please use the [Canary](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem) build and let us know what you think

**Comment by jechols** [comment] 2019-08-29 21:50
I think this is good!  Thanks so much for the crazy-fast response and fix!  Loving the tool so far FYI

**Comment by ferBonnin** [comment] 2019-09-05 21:19
Closing since this fix is now in production :)

**Closed by ferBonnin** 2019-09-05 21:19 UTC
Labels: bug, status: resolved
