### ISSUE TITLE
Preview Features heading overlaps with text underneath it when scrolling

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#5840] opened 2022-07-28 19:06 UTC
## Describe the bug

When enough preview features are visible to result in the preview features panel having a scroll bar, it is possible to enter a state where the "Preview Features" heading at the top of the panel is sticky but its background is not, so you end up with the panel's content and the heading getting drawn over each other.

![screenshot with overlapped text in preview features panel](https://user-images.githubusercontent.com/376284/181616945-cbeaba2a-c53a-4935-b2e8-bbc2e9d231d9.png)

This is probably low impact/priority overall because in practice we don't have that many preview features unless you use dev tools to show hidden-by-default feature flags.

**To Reproduce**

1. Open canary or dev AI4Web
2. Enable hidden feature flags by opening from background page dev tools console and entering `insightsFeatureFlags.enableFeature('showAllFeatureFlags')`
3. Ensure that the details view is closed
4. **using the popup/launchpad gear menu** (*not* the details view gear menu), open "Preview Features"
5. Scroll down in the Preview Features panel

(note that the repro will be lost if you resize the window, or if you close/reopen the preview features panel from within the details view)

## CodePen repro example

n/a

## Expected behavior

Text shouldn't overlap. The heading behavior should probably be consistent with Settings, where the heading isn't sticky.

## Screenshots

see above

## Context (please complete the following information)

- OS Name & Version: Windows 11 22000.795
- AI-Web Version & Environment: Canary 2022.7.27.1622 (and dev from main as of writing)
- Browser Version: Edge stable 103.0.1264.71
- Target Page: n/a

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

n/a

**Comment by ferBonnin** [comment] 2022-09-12 23:28
closing as this no longer repros

**Comment by dbjorge** [comment] 2022-11-10 20:09
@ferBonnin and I discussed offline - it turns out the repro conditions are more specific than I'd originally written in the bug, but she's confirmed that she can also repro the issue with more specific steps. I'll edit the description with more specific repro steps.

**Comment by peterdur** [comment] 2023-03-30 20:04
Looks like this has been addressed by FluentUI in their https://github.com/microsoft/fluentui/pull/25665, work required is update plus validate no UX/A11y regressions. See also #6033.

**Comment by DaveTryon** [comment] 2023-05-04 19:36
Internal feature https://dev.azure.com/mseng/1ES/_workitems/edit/2062851 is tracking the work for a FluentUI update. Moving this to blocked while we wait for that feature to start.

**Comment by DaveTryon** [comment] 2023-06-29 23:31
This will get fixed when we are able to update to a more recent of @fluentui.

**Comment by v-viyada** [comment] 2024-06-19 17:28
This is fixed by upgrading fluent ui v8 to latest in https://github.com/microsoft/accessibility-insights-web/pull/7336

**Comment by v-sharmachir** [comment] 2024-06-21 13:59
This is released in version 2.43.0

**Closed by v-sharmachir** 2024-06-21 13:59 UTC
Labels: bug
