### ISSUE TITLE
False positive for aria-required-children in listbox

### ISSUE THREAD

**Issue by Anschur** [microsoft/accessibility-insights-web#6462] opened 2023-03-01 14:30 UTC
## Describe the bug

I will get a aria-required-children error in a listbox, if there are any elements with role="presentation" between the _listbox_ and the _options_. I do believe elements with role="presentation|none" should be disregarded from this rule and not be counted as an "illegal" child.

**To Reproduce**

1. Go to https://a11y-screenreader-demos.netlify.app/studies/secondary-actions/ 
2. Scroll down to 'Listbox with buttons adjacent to options'
3. Run AI FastPass

## Expected behavior

No not think role="presentation" should impact the children of listbox, as they are to be disregarded by AT.

## Screenshots
![image](https://user-images.githubusercontent.com/38563783/222168799-ab08c143-053c-4f7b-a9d1-bcd592fe839f.png)

![image](https://user-images.githubusercontent.com/38563783/222168957-a12dc327-1995-4623-a57c-dff4bf420bf3.png)

## Context (please complete the following information)

- OS Name & Version: 
- AI-Web Version & Environment: 2.37.3
- Browser Version: 
- Target Page:

**Comment by sfoslund** [comment] 2023-03-01 16:55
Hi @Anschur, thanks for using Accessibility Insights! I have investigated this issue and repro'ed, but I do not believe it is a false positive. The cause seems to be the remove option buttons on the right hand side of the menu items. The current implementation of the page has those buttons alongside the menuitems, when they visually appear to be a subelement of the menuitem. This is confusing for adaptive technologies and right now this listview is difficult to navigate with a screenreader as there is no indication of the close button unless you know to navigate to it, and even then it is announced just as `X` (instead of `close button` or some other meaningful name). I think the fix here would be to nest the close button inside the menuitem, I have tested it and this fixes the aria-required-children issue you're seeing. 

Let us know if you have any further questions, thanks!

**Comment by Anschur** [comment] 2023-04-24 07:33
Thanks for your reply @sfoslund . You are right. Removing the adjacent buttons, will remove the error. Nesting the button inside the option, as you suggest, will not trigger this error but it will trigger a nested interactive error (see example above previous):
![image](https://user-images.githubusercontent.com/38563783/233928598-12b4b4c4-ee86-4638-a5ff-4601734146a4.png)
Do you see any way of having secondary actions on listbox items that will not cause issues for AT/AI?

**Comment by JGibson2019** [comment] 2023-04-25 18:48
Hi @Anschur; thanks for reaching back out! The right way to code secondary actions for listbox items is a design question, and outside of the scope of our support. We do recommend that you reach out to your organization's accessibility champs or design team to see if they can provide guidance around best practices. Many will offer office hours where they can sit down and provide direct advice. In the meantime, I also recommend taking a look at the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role#best_practices) and the [ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/) to see if the best practices and examples there can answer your question!

Regarding this issue, since Sarah determined this was not a false positive, I'll be closing this out. Best of luck moving forward and feel free to reach out with other questions around potential false positives or bugs with the tool.

**Closed by JGibson2019** 2023-04-25 18:48 UTC
Labels: status: needs attention, status: no recent activity
