### ISSUE TITLE
Scan fails when a page does not have a body tag

### ISSUE THREAD

**Issue by haonliu** [microsoft/accessibility-insights-web#1107] opened 2019-08-20 21:25 UTC
## Describe the bug

Scan fails when a page does not have a body tag

**To Reproduce**

1. Create a page with the following html: 
 ````
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>

<h1>Hello world</h1>

</html>
````
2. Open AI-web
3. Run automated checks
4. See error in the console

## Expected behavior

The scan should be able to run.

## Extension (please complete the following information)

- OS: any
- Version any
- Browser Version any
- Target Page N/A

**Comment by dbjorge** [comment] 2020-01-23 22:45
I don't think we intended to close this or tag it as needs author feedback, looks like this was just lost in upkeep.

I found that the repro steps from the original bug didn't work as-is; Chrome normalized the repro content as having a body tag. However, using content of `<frameset></frameset>` does cause the issue, where running a fastpass hangs with a scanning spinner and the injected page shows the following error:

```
injected.bundle.js:97 Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
    at n.create (injected.bundle.js:97)
    at ae.initialize (injected.bundle.js:97)
    at ae.initialize (injected.bundle.js:97)
    at Object.<anonymous> (injected.bundle.js:97)
    at Object.<anonymous> (injected.bundle.js:97)
    at n (injected.bundle.js:2)
    at Object.<anonymous> (injected.bundle.js:97)
    at n (injected.bundle.js:2)
    at injected.bundle.js:2
    at injected.bundle.js:2
```

To clarify on @ferBonnin 's last question, this is our limitation, not axe-core's; I verified on the above minimal test page and the internal page that the same issue was recently re-raised for that reproduces the issue that axe-core and axe's chrome extension work fine.

**Comment by ferBonnin** [comment] 2020-01-23 22:46
@dbjorge no. It needed a reply from Wahaj.
.@waabid is this our limitation or axe-core's?

**Comment by dbjorge** [comment] 2020-01-23 22:49
@ferBonnin, I already clarified in the reopening comment: this is our issue, axe-core and axe's web extension both work fine on all repro variants.

**Comment by waabid** [comment] 2020-01-23 23:44
Sorry, I must have missed this from before! Dan is correct: we should be able to function even without a body element. My guess is we make this assumption in a few places and can likely replace it with html element (but this is just an educated guess).

**Comment by ferBonnin** [comment] 2020-01-27 21:10
per conversation with Peter, there are 2 issues:

1. we hang
1. we don't scan framesets.

Suggestion for this is (in parallel)

- add a fix so we dont hang
- either scan the frameset or create a rule (contribute back to Deque) that tells the users that framesets are obsolete

**Closed** 2020-05-20 21:03 UTC
Labels: bug, status: needs investigation
