### ISSUE TITLE
Enable possibility for partials assessments via "not tested" or "skipped"-option and custom assessment templates

### ISSUE THREAD

**Issue by MarcusMorba** [microsoft/accessibility-insights-web#5672] opened 2022-06-25 04:11 UTC
## Is your feature request related to a problem? Please describe.

Doing a full assessment takes much time, for a first audit I want to focus on the most critical areas (focus visible, keyboard access etc.) Contrast issues often require a more complex review and fixing as design department is included, especially when a design system is used, therefore I would love the option to skip tests.

## Describe the desired outcome

Be able to skip a test and mark it with "not tested" or "skipped"

## Describe alternatives you've considered

Mark it as "fail"

## Additional context

Ideally I could create different templates for different assessments and define which tests I want e.g. for our developers > developer essentials, for our designers > designer essentials etc.

**Comment by ferBonnin** [comment] 2022-06-27 17:16
duplicate of #3228?

**Comment by ferBonnin** [comment] 2022-07-05 18:59
After discussing this with the team, we talked about how the default state of _incomplete_ can be used as not-tested or skipped. We recommend leaving skipped tests as is so they appear in the report as _incomplete_

**Closed** 2022-07-05 19:00 UTC
Labels: resolution: out of scope, feature request, status: needs author feedback

**Comment by MarcusMorba** [comment] 2022-07-17 09:07
Ok to close, but I still would see "incomplete" not as a proper solution for "not tested/skipped" steps.
