### ISSUE TITLE
Jerky Dialog Box

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#578] opened 2019-04-22 19:04 UTC
## Describe the bug

For some links the dialog box jitters in a way which could cause people with epilepsy problems. I'm not sure why it is flickering like this. The screenshot doesn't demonstrate it but the video does.

**To Reproduce**

I'm having this issue on the second color contrast link on https://tastybackend.com/

Chrome, MacOSX. 

## Expected behavior

It shouldn't flicker.

## Screenshots

<img width="616" alt="Screen Shot 2019-04-22 at 2 58 18 PM" src="https://user-images.githubusercontent.com/116832/56519179-67173600-650f-11e9-846b-6c8e711c2c27.png">

https://drive.google.com/file/d/1CmPOQ9byiIr2471KjCovNJiUwP0bsJDK/view

**Comment by dbjorge** [comment] 2019-04-22 22:27
Thanks very much for this report! We've been able to reproduce and root cause this; it's caused by a particularly bad conflict between the target page's CSS and our dialog's. The target page here is applying a "border: 3px" to all hovered buttons but not unhovered buttons; the extra 6px ends up re-flowing the row of 3 buttons at smaller screen widths, and the re-flow happens in such a way that if your mouse is positioned right, it can move the button out from under the mouse, resulting in a back-and-forth flickering of reflowing.

We'll release a fix for this right away that:
* Suppresses border styling from applying to the dialog's buttons
* Slightly increases the minimum width of the dialog, to make it less likely to see this sort of reflow in the case that a target page happens to introduce some other type of small width bump

**Comment by dbjorge** [comment] 2019-04-23 00:37
Fix is available in [Canary](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem) build 2019.4.22.2339. It will go out to production with our next release train.

**Comment by ferBonnin** [comment] 2019-05-10 17:42
Hi @mgifford the fix for this is now in Production build version 2.3.0 :)

**Closed** 2019-05-13 14:54 UTC
Labels: bug, status: resolved
