### ISSUE TITLE
Export report dialog with Magnifier shifts when typing

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#3538] opened 2020-10-27 19:02 UTC
## Describe the bug

When using magnifier, the export report dialog moves unexpectedly when typing (specially if deleting text)

**To Reproduce**

Open Magnifier
1. Run automated checks in an Android app
2. select export report button
3. type some text and delete some text
notice how the text box moves when typing and moves erratically when deleting text.

## Expected behavior
the text box should not move erratically. 

## Context (please complete the following information)

- OS Name & Version:  Windows 
- AI-Web Version & Environment:  Android

## Additional context
From Peter, looking at the text-shifting video it seems like Magnifier is toggling between centering on the text cursor and centering on the mouse pointer. Not clear, but possible, that there's behavior on our part that is triggering this.

**Comment by karanbirsingh** [comment] 2020-12-08 23:24
@ferBonnin I tried running Magnifier on notepad.exe, a [native HTML <input> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) in Edge / Chrome, and Accessibility Insights. For me all experiences kept the text cursor in the center, so each character change moved the border. I wonder if this is expected behavior or if you had a different experience.

**Comment by ferBonnin** [comment] 2020-12-09 00:04
sent link to two videos to @karanbirsingh. Can only reproduce in Unified.

**Comment by karanbirsingh** [comment] 2020-12-09 21:38
I am able to reproduce this with a minimal electron application with a simple textarea. A minimal sample app can be downloaded [here](https://github.com/karanbirsingh/sample-electron-textarea-app).

When Magnifier zooms in such that the textarea exceeds the size of the screen, typing leads to 'jumping' behavior where the Magnifier bounds alternate between centering on the text cursor and what seems like the full textarea. For me this occurs with a single-monitor setup at 1920x1080 at 150% resolution, with 300% magnifier zoom.

**Comment by ferBonnin** [comment] 2020-12-09 21:44
thanks @karanbirsingh! taking this out of the board and keeping it as needs investigation to follow up.

**Comment by karanbirsingh** [comment] 2020-12-21 18:26
Updating with smaller video showing Magnifier "jumping" behavior:
https://user-images.githubusercontent.com/7775527/102809317-9e8a5580-4376-11eb-84fb-b9c54769a7c1.mp4

So far it seems the root cause is "extra" Focus events raised by textareas in Electron. Magnifier seems to react to the intermittent events and the viewport shifts.

Here are event recording logs:
```
UIA:FocusEvent Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:AutomationEvent    [Text_TextChanged] Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:AutomationEvent              [Text_TextSelectionChanged] Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:AutomationEvent    [Text_TextChanged] Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:FocusEvent Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:AutomationEvent    [Text_TextChanged] Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:AutomationEvent              [Text_TextSelectionChanged] Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
UIA:AutomationEvent    [Text_TextChanged] Sender: ControlType:UIA_EditControlTypeId (0xC354), Name:""
```

In the Chrome or Edge browsers, extra focus events are not raised when typing in a textarea, and we don't see the odd jumping behavior. Seeing if this is something that is better handled in Magnifier or if there's an issue in Electron's event-raising

**Comment by karanbirsingh** [comment] 2022-10-04 18:01
This is blocked on https://github.com/electron/electron/issues/27826

**Comment by DaveTryon** [comment] 2023-04-22 00:34
We won't be fixing this

**Closed by DaveTryon** 2023-04-22 00:34 UTC
Labels: bug, category: accessibility, status: blocked
