### ISSUE TITLE
scrolling overlap of title and content on info and examples page of assessment requirement 

### ISSUE THREAD

**Issue by shanisebarona** [microsoft/accessibility-insights-web#6033] opened 2022-09-13 21:58 UTC
## Describe the bug

When opening the info and examples panel of a test section requirement, the title of the requirement overlaps with the content in the panel. 

**To Reproduce**

1. Click on the extension icon and select 'Assessment'.
2. Click on any test section between 2 - 24 on the left panel. 
3. Select a requirement in a test section and click the `i` icon next to the requirement title at the top of the page. 
4. When the right hand overlap panel appears, if it is scrollable, scroll until the title of the requirement overlaps with the rest of the content. 

## Expected behavior

The title of the requirement in the open panel should behave like the rest of the text in the panel and not remain sticky on scroll. 

## Screenshots

![overlap_bug](https://user-images.githubusercontent.com/18401275/190013894-268174fb-c10a-47af-a11b-886dc439872c.gif)

## Context (please complete the following information)

- OS Name & Version: Windows 11 Enterprise / Surface 3
- AI-Web Version & Environment: Production 2.34.1 
- Browser Version: Google Chrome Version 105.0.5195.125 (Official Build) (64-bit) and Microsoft Edge Version 105.0.1343.33 (Official build) (64-bit)
- Target Page: Any.

## Are you willing to submit a PR?
Yes.

## Did you search for similar existing issues?
Yes.

**Comment by ferBonnin** [comment] 2022-09-14 23:00
Adding a note for when triaging, I cannot repro this consistently. changing the zoom level / window size makes this issue appear / dissapear

**Comment by peterdur** [comment] 2023-02-11 00:01
Moving to re-triage since this has been addressed by FluentUI in their [PR 25665](https://github.com/microsoft/fluentui/pull/25665), work required is update plus validate no UX/A11y regressions

**Comment by DaveTryon** [comment] 2023-05-02 23:24
I've confirmed that a newer version of fluentui (see #6606) will fix this. Due to the impact of updating fluentUI, though, I'm marking this as blocked until we schedule a feature to get a new version and perform a full accessibility pass

**Comment by DaveTryon** [comment] 2023-05-04 19:31
Internal feature https://dev.azure.com/mseng/1ES/_workitems/edit/2062851 has been created to track the work to refresh FluentUI

**Comment by DaveTryon** [comment] 2023-06-29 23:32
This will get fixed when we are able to update to a more recent version of fluentui.

**Comment by JGibson2019** [comment] 2024-02-05 19:13
Considering this a duplicate of #5840

**Closed by JGibson2019** 2024-02-05 19:13 UTC
Labels: bug, status: blocked
