### ISSUE TITLE
Cards UI aren't table-navigable when using AT

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#1494] opened 2019-10-16 20:17 UTC
## Describe the bug

The failed instance cards in the universal cards UI aren't navigable as a table when using AT. 

**To Reproduce**

1. Ensure that the "Enable universal cards UI" feature flag is on.
2. Start running a screen reader, such as NVDA or JAWS.
3. Go to [Accessible University (Inaccessible version)](https://www.washington.edu/accesscomputing/AU/before.html) or any website with accessibility issues.
4. Open the Accessibility Insights popup and select "FastPass"
5. On the resulting automated checks page, tab to a failure instance card.
6. The screen reader announces the card as a "table with 1 columns and 3 rows."
7. While holding down CTRL + ALT, use the arrow keys to navigate through the table.
8. Hear or see from NVDA's speech viewer that the values of Path, Snippet, and How to fix can't be reached with this navigation. NVDA announces "edge of table," and JAWS announces "end of row."

## Expected behavior

The card should be announced as a table with 2 columns and 3 rows, and the values for Path, Snippet, and How to fix should be reachable when navigating the card as a table with the AT.

## Extension (please complete the following information)

- OS: Windows
- Version: 10.0.18362 Build 18362
- Browser Version: Chrome 77.0.3865.120 (Official Build)
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html
- Extension version: Canary 2019.10.16.x

## Are you willing to submit a PR?

Yes, but this might require a greater amount of time to investigate the root cause and potential solutions. A previous feature team has already spent a significant amount of time investigating a similar issue in the cards of the report UI (see section [Additional context](#additional-context) below).

## Did you search for similar existing issues?

Yes

## Additional context

The cards in the report UI (FastPass > Export result) have a similar but slightly different issue with AT table navigation. JAWS reads "table with 1 of 0 columns and 3 of 0 rows," so table navigation does not work as expected. NVDA does not recognize the card as a table.  These cards should be updated, so they work the same way as the cards in automated checks.

**Comment by ferBonnin** [comment] 2019-10-16 22:16
Checked an old report (we had tested the report before with users who are blind without encountering this) , this should not be announced as a table, sounds like a regression.

**Comment by ferBonnin** [comment] 2019-10-17 23:37
Per Adarsh, this is expected behaviour. Tested that this is the same behaviour as an old report although NVDA decides to not announce the table and Jaws does.

**Comment by ferBonnin** [comment] 2019-10-17 23:39
Assigning to Rob since he mentioned this; please let us know if you agree.

**Comment by karanbirsingh** [comment] 2019-10-31 17:03
For NVDA, here is the behavior we see in the report in 2.10.3 (production).
- pressing "tab" to get to the card leads to focus on the card. Pressing any arrow key or shortcut key from this point does not lead to the content of the card being read (only the first card row, which gets read by default when first focused on the card. The CTRL+ALT+arrow combinations also do not lead to any cell
- before tabbing to the card, NVDA does recognize a "T" to get to the table. At this point arrow keys work properly to navigate through each table
- pressing "T" while focused on the card (after getting there from tabbing) does not go to the table
- if focused on something other than the card, pressing down and up arrows reads through all the content in the card as well (similar to scan mode)

at the very least, it seems like being focused on the card disallows arrow key & 'T' input from NVDA

**Comment by ferBonnin** [comment] 2019-11-04 21:09
@karanbirsingh this is a different bug. Could you please file a new but with detailed info?

Thanks!

**Closed** 2019-11-04 21:09 UTC
Labels: bug
